### ISSUE TITLE
Cannot interact with Anjay's UDP port

### ISSUE THREAD

**Issue by MatthiasVanEeghem** [AVSystem/Anjay#11]
Hello,

I'd like to interact directly with Anjay instead of going through an LwM2M server. I've set the --port option to 5685 in Anjay, so I have a static port. Every time I try to read a resource via a CoAP packet, I get a "port unreachable" error.  Moreover, I also dont see any UDP port open on port 5685.

If I run Wireshark I can see the requests from an LwM2M server (Leshan in my case) do work however. I'm not sure why the same UDP requests to the same port would not work? There's no error in the console, no message from Anjay at all.

I'm guessing there is a port unreachable error because Anjay doesn't reply to the ICMP's echo message, but shouldn't I still be able to send some CoAP requests to it?

Thank you in advance!

**Comment by dextero** [comment]
Hi Matthias,

Anjay will not accept packets from endpoints not recognized as LwM2M servers. Make sure your CoAP packets are sent from an address configured as a server.

I quickly checked it with `netcat`, and it seems to work fine if the "server" is up before starting Anjay demo client:

Terminal 1:
```
$ nc -u -l 5683 <<<"foo" # dummy invalid response to initial Register
... some garbage (CoAP headers) ...
ep=urn:dev:os:0023C7-00000lt=86400�</1/1>,</2>,</3/0>,</4/0>,</5/0>,</6/0>,</7/0>,</10/0>,</11>,</1337>,</11111/0>,</12359/0>,</12360>,</12361/0>
```

Terminal 2:
```
$ ./output/bin/demo --server-uri coap://127.0.0.1:5683
... lots of stuff ...
2017-10-26 17:47:08.320347 TRACE [avs_coap] [/home/marcin/projects/anjay/avs_commons/git/coap/src/ctx.c:189]: send: 0.02 Post, CONFIRMABLE, id 11915, token 26bd805f0af144f3 (8B)
2017-10-26 17:47:08.320539 DEBUG [avs_coap] [/home/marcin/projects/anjay/avs_commons/git/coap/src/msg.c:186]: missing/incomplete token (got 0, expected 6)
2017-10-26 17:47:08.320548 DEBUG [avs_coap] [/home/marcin/projects/anjay/avs_commons/git/coap/src/ctx.c:275]: recv: malformed message
... more stuff ...
```

Please note that Anjay will only accept incoming requests after the "LwM2M server" correctly responds to the initial Register message.

I hope that helps!

**Comment by MatthiasVanEeghem** [comment]
That definitely helped me! Thank you so much for the information!

**Comment by dextero** [comment]
I'm glad to hear that :smile:
