### ISSUE TITLE
Compile in Centos

### ISSUE THREAD

**Issue by rkimsb2** [AVSystem/Anjay#12]
When I running cmake in centos, EC Factory support issue has occured in keytool command.
I solved this problem by install oracle jdk locally. And it also can be solved by editing security.properties in openjdk directory of centos.

Hope centos installation be added in guide.

**Comment by dextero** [comment]
If I understand you correctly, the OpenJDK keytool does not support EC by default and fails to generate certificates.

I checked the build on `centos:6` and `centos:7` docker images using OpenJDK `1.7.0.161-2.6.12.0.el6_9` and `1.8.0.151-1.b12.el6_9`, and there were no issues with keytool in default configuration. Which versions of CentOS and OpenJDK do you use?

Anyway, we will add build instructions for CentOS in next release. Thank you for the suggestion!

**Comment by rkimsb2** [comment]
here's my test environment.

CentOS Linux release 7.2.1511 (Core)
OpenJDK Runtime Environment (build 1.8.0_151-b12)

And when i running cmake, i got this message.
Importing keystore client.p12 to keyStore.jks...
keytool error: java.security.UnrecoverableKeyException: Get Key failed: EC KeyFactory not available
CMake Error at CMakeLists.txt:481 (message):
  could not generate SSL certificates

**Comment by dextero** [comment]
README now contains build instructions for CentOS7 (https://github.com/AVSystem/Anjay#centos-7).

After following these instructions on a clean CentOS 7.2.1511 installation the `EC KeyFactory not available` error did not occur.

**Comment by rkimsb2** [comment]
I checked it doesn't happen in latest version of Centos.

my problem was occured from this [issue](https://bugzilla.redhat.com/show_bug.cgi?id=1312593).
it only happen on upgrading old openjdk to new.

i fixed this issue by overwriting java.security.rpmnew to java.security.
