### ISSUE TITLE
cmake warnings

### ISSUE THREAD

**Issue by mkarthikdevops** [AVSystem/Anjay#15]
Hi 
Please find the cmake warnings.. I will be using DTLS in my bootstrap and device registration 
But when i try to compile for Anjay simulator client , I got following warnings in cmake.
I doubt because of this reason the demo client could not create or connect CoAP sockets, etc.

I tried all DTLS backend option . In most of them the error /warning is like below. Pls suggest to solve the problem.
My environment: UbuntuVM installed in Oracle virtualbox+vagrant in local (Win OS)laptop , connected to Test server by public network

vagrant@vagrant:~/Anjay$ cmake . -DDTLS_BACKEND="openssl"
-- Looking for dlsym() in library:
-- Looking for dlsym
-- Looking for dlsym - not found
-- Looking for dlsym() in library: dl
-- Looking for dlsym
-- Looking for dlsym - found
-- Checking if IN6_IS_ADDR_V4MAPPED is usable
-- Checking if IN6_IS_ADDR_V4MAPPED is usable - no
-- DTLS backend: openssl
-- Could NOT find tinyDTLS (missing:  TINYDTLS_INCLUDE_DIR TINYDTLS_LIBRARIES TINYDTLS_VERSION)
-- Checking if IN6_IS_ADDR_V4MAPPED is usable
-- Checking if IN6_IS_ADDR_V4MAPPED is usable - no
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vagrant/Anjay

Rgds
Karthik M

**Comment by dextero** [comment]
Hi,

I'm afraid I don't really understand what warnings/errors are you referring to. Attached output looks perfectly fine and contains only usual status messages.

- `dlsym()` is only required for C unit tests. If all you need is to compile the demo client, it's perfectly fine to not have it available.
- `IN6_IS_ADDR_V4MAPPED` check is performed to enable an optional workaround for systems where such macro is defined, but does not work. The code will work either way.
- Anjay may use one of three possible DTLS libraries: OpenSSL, mbed TLS or tinyDTLS. Even though TinyDTLS was not found, the log suggests OpenSSL can be used, which is good enough.

The final `-- Build files have been written to: /home/vagrant/Anjay` message indicates that there are no errors, and you may continue compiling the project.

Are there any compilation issues when you run `make`? If there are any, please upload full logs from both CMake and make.

Best regards,
Marcin
