### ISSUE TITLE
Storing bootstrapped connection info

### ISSUE THREAD

**Issue by chelliwell** [AVSystem/Anjay#19]
I have a client app derived from the 'demo client', which I am using with bootstrapping. I'm trying to figure out if there is a way to 'hook' the response from the Bootstrap Server so that I can save the _Server_ connection info to use on next reboot (i.e. instead of just re-bootstrap each time).
Has anyone done this, and know where/how to grab the info?

**Comment by kFYatek** [comment]
"Hooking" the Bootstrap Information isn't directly possible, but persisting the Server and Security object contents may allow you to do what you need. See the [relevant tutorial](https://avsystem.github.io/Anjay-doc/AdvancedTutorial/AT2.html).

**Comment by chelliwell** [comment]
Thanks, I've been experimenting with the Persistence functions, and I can see how to tie this into one of the various avs_stream methods. I may need to implement my own, because I am writing to a region of Flash memory which needs a single 'commit'/'flush' at the end (i.e. it I can't do sequential writes such as on a file).  
However I can't see whether the object persistence modules (e.g. server_persistence.c) ever call avs_stream_v_table_t.finish_method ...? (which I would need for doing my write of the accumulated object data to Flash). Or should I implement a 'close' in my custom stream handler?
