### ISSUE TITLE
Support for mbed-os?

### ISSUE THREAD

**Issue by syhoangmai** [AVSystem/Anjay#20]
Hi, I want to use this library to connect a microcontroller running mbed-os to a generic lwm2m server (e.g Leshan). Do you have any plan of making this library works with mbed-os? Thank you!

**Comment by dextero** [comment]
Hi,

Currently Anjay in the form of mbed OS library is only available for commercial customers. May I know what do you intend to use the LwM2M client for, and what microcontroller are you using?

**Comment by syhoangmai** [comment]
I am planning to use lwm2m for device management, firmware update (if possible) and sensor data report. My device will be based on stm-l4 with nb-iot modem. Where should I contact for official/commercial support?

By the way, I see there is an advertisement about Anjay LwM2M SDK for STM32CubeMx. If possible, could you tell me when it will be released? Thank you!

**Comment by dextero** [comment]
> Where should I contact for official/commercial support?

Please send an email to sales@avsystem.com.

> I see there is an advertisement about Anjay LwM2M SDK for STM32CubeMx. If possible, could you tell me when it will be released?

We are currently working with ST to get their approval for publishing the STM32Cube package with an example project for [P-L496-CELL01](https://www.st.com/en/evaluation-tools/p-l496g-cell01.html)/[P-L496-CELL02](https://www.st.com/en/evaluation-tools/p-l496g-cell02.html). Unfortunately, at this moment I'm unable to give you any specific dates.
