### ISSUE TITLE
OMA version 1.1 support

### ISSUE THREAD

**Issue by sgoyaldel** [AVSystem/Anjay#21]
Hi,

May i get following information related to OMA version 1.1 support in code  ?
1. COAP over SMS
2. CBOR support
3. TCP support
4. OSCORE support

**Comment by dextero** [comment]
Hi,

Right now, support for LwM2M 1.1 is only available in the commercial version of Anjay, which significantly extends the open-source version published on Github. Please contact sales@avsystem.com for details, including the current state of LwM2M 1.1 feature support.

Best regards,
Marcin
