### ISSUE TITLE
[yocto] How can i build anjay in yocto?

### ISSUE THREAD

**Issue by Fermata39** [AVSystem/Anjay#22]
How can i build anjay in yocto?

I am bring up anjay in yocto.

but did occur the build error.
[Work Flow]
1. create recipe for anjay
2. do git clone to custom directory in yocto
3. do start build for bitbake

[Error]
243 src/mbedtls/mbedtls_persistence.c:18:30: fatal error: mbedtls/platform.h: No such file or directory
244  #include <mbedtls/platform.h>
245                               ^
246 compilation terminated.
247 make[2]: *** [avs_commons/git/net/CMakeFiles/avs_net.dir/src/mbedtls/mbedtls_persistence.c.o] Error 1
248 make[2]: *** Waiting for unfinished jobs....
249 src/mbedtls/mbedtls.c:18:30: fatal error: mbedtls/platform.h: No such file or directory
250  #include <mbedtls/platform.h>
251                               ^
252 compilation terminated.
253 make[2]: *** [avs_commons/git/net/CMakeFiles/avs_net.dir/src/mbedtls/mbedtls.c.o] Error 1
254 In file included from src/mbedtls/data_loader.c:23:0:
255 src/mbedtls/data_loader.h:19:25: fatal error: mbedtls/ssl.h: No such file or directory
256  #include <mbedtls/ssl.h>

[Request]
1. Did you try to bring up the anjay in yocto?
If you did it, please share the guide.

2. I checked the makefile in the av system, but it was complicated,
please share the guide for "mbedtls" lib.

many thanks
shinkook

**Comment by sznaider** [comment]
We haven't tried that really, but since Yocto supports CMake, and Anjay uses CMake as well, it shouldn't be a big problem to make it compile.

You mentioned there was a compile time error. Could you be more specific?

**Comment by sznaider** [comment]
OK, I see you modified your first post -- it would be less confusing if you responded instead, please prefer doing so in the future (there's no notification about an edit).

Looks like mbedTLS headers could not be found, which is rather unexpected if CMake found mbedTLS in the first place, which it had to, or otherwise you'd get an error at configuration stage.

You said you were looking at raw Makefiles -- you shouldn't, they're autogenerated by CMake and are not intended to be modified in any way. You should try to use cmake in your Yocto recipe.

If you want to know more about somewhat non-standard build process, with manual compilation of TLS libraries, please take a look at [our documentation](https://avsystem.github.io/Anjay-doc/Compiling_client_applications.html).

**Comment by chelliwell** [comment]
I don't want to make accusation lol, but I have done quite a lot of work with yocto/bitbake and adding in new packages/recipes from outside the yocto tree. I have had problems before where the cross-compilation abilities of the cmake was not robust - e.g. cmake thinks you have a package but has found it on the native system; but when yocto comes to build it, the headers etc aren't found in the _yocto_ build directories.
One question for the OP would be: have you added mbedTLS into your yocto build?

**Comment by Fermata39** [comment]
Dear chelliwell

Thanks for your comment.

I did install mbedTLS package using bitbake(ver.mbedtls_2.13.0)
[reference info for mbedTLS]
http://cgit.openembedded.org/meta-openembedded/tree/meta-networking/recipes-connectivity/mbedtls/mbedtls_2.13.0.bb

But still did occur the build error for anjay.

[Error Comment]
make[2]: *** No rule to make target `MBEDTLS_LIBRARY-NOTFOUND', needed by `output/lib/libanjay.so.1.0.0'.  Stop.

I don't know why this error did was occurred.

as your comment,
after did install mbedTLS , then did build the anjay but didn't success it.

would you please check it?

many thanks
shinkook.kim

**Comment by terravi** [comment]
I have the same error. Do you have any suggestion?

**Comment by terravi** [comment]
I'm using the following anjay recipe:

`DESCRIPTION = "Anjay project"

SECTION = "anjay"
DEPENDS = "mbedtls-native"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=e3fc50a88d0a364313df4b21ef20c29e"
FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}-${PV}:"
SRCREV = "master"
SRC_URI = "gitsm://github.com/AVSystem/Anjay.git;protocol=https"
SRC_URI[sha256sum] = "00054bd042ee5bb1c1b09b47412abfb190904b4904f464f37042b984302c3742"
S = "${WORKDIR}/git"

inherit cmake`

**Comment by terravi** [comment]
I solved patching  the file git/avs_commons/git/cmake/FindMbedTLS.cmake. 

--- git/avs_commons/git/cmake/FindMbedTLS.cmake 2019-10-11 12:44:07.104553200 +0200
+++ FindMbedTLS_vte.cmake       2019-10-17 11:19:19.593121300 +0200
@@ -65,7 +65,7 @@
 if(MBEDTLS_ROOT_DIR)
     # Disable re-rooting paths in find_path/find_library.
     # This assumes MBEDTLS_ROOT_DIR is an absolute path.
-    set(_EXTRA_FIND_ARGS "NO_CMAKE_FIND_ROOT_PATH")
+    set(_EXTRA_FIND_ARGS "${CMAKE_SYSROOT}")
 endif()

 find_path(MBEDTLS_INCLUDE_DIR
