### ISSUE TITLE
How to make "APN connection profile" instance automatically?

### ISSUE THREAD

**Issue by Soohyun-Hong** [AVSystem/Anjay#28]
Hi,

When I connect lwm2m server, server add "LwM2M Access Control, APN connection profile & Porfolio" object but does not add instance.
(LwM2M Server, Device, Firmware Update, Location, Connectivity Statics & Cellular connectivity  Object/Instance is added well.)

Has anyone had a experience before?

Regards,
Sean

**Comment by dextero** [comment]
Hi,

Some LwM2M objects allow the server to add new instances by using the Create operation. In Anjay demo client, APN Connection Profile is one of such objects - it does not have any instances initially, but the server can create new ones at runtime.

Best regards,
Marcin

**Comment by Soohyun-Hong** [comment]
Then, how can I make (Access Control, APN connection profile, Porfolio)instance initially? 
Is it impossible?

**Comment by sznaider** [comment]
Hi,

I believe your questions can be answered by our [exhaustive tutorials on LwM2M Objects in Anjay](https://avsystem.github.io/Anjay-doc/BasicTutorial/BT5_CustomObject.html). Please refer to them for more details.

Also, please note that on github, we provide support in case of bugs found in the library. If you are interested in a personalized support (integration, etc.), please contact sales@avsystem.com.

Best regards,
Mateusz
