### ISSUE TITLE
Anjay + Coiote fails SET requests for Bootstrap-Awareness

### ISSUE THREAD

**Issue by ThinkpadX200** [AVSystem/Anjay#37]
I'm seeing an issue using the bootstrap-awareness example in Anjay where a Coiote specified bootstrap server is unable to SET parameters on a registered device. Attached are logs from the bootstrap server.

The client says "received packet is not a valid CoAP message" in addition to "Bootstrap Server misused Security Object". The client will then time out of the Bootstrap Finish. Logs on the bootstrap server seem to show a proper BootstrapWrite command being sent to the client, but the client returns a "4.00 BadRequest". The server logs are attached.

I was seeing issues with other examples, getting 4.03 CoAP errors. I would assume this has something to do with an underlying CoAP mishap, but I figured I'd post here. If it matters, I'm using the master branch of Anjay compiled onto an Arm architecture.

**Comment by kFYatek** [comment]
Thank you for reporting the issue. Unfortunately, I'm not quite sure what might be the root cause. It would be very helpful if you could provide:

- PCAP of the communication with server, captured using e.g. `tcpdump`
- Full client-side logs, preferably on the TRACE level
  - to set log level, please add a `avs_log_set_default_level(AVS_LOG_TRACE);` call before initializing Anjay
  - for the TRACE-level logs to work, you will also need to enable `AVS_LOG_WITH_TRACE` Anjay's CMake configuration option, i.e. add `-DAVS_LOG_WITH_TRACE=ON` to CMake command line

**Comment by ThinkpadX200** [comment]
The client examples in Anjay seem to not have knowledge of "avs_log_set_default_level()". A grep for that function in the Anjay top level directory returns nothing. Is there a header file I'm missing, or perhaps a client that has that capability already?

**Comment by ThinkpadX200** [comment]
Here is the updated trace logs. I'm noticing a couple oddities, such that the server is requesting a read of objects that don't exist like /3 and /3301/. I'm confused why /3 seems to be a mandatory object when the only specified objects defined by Anjay are /0 and /1.

[anjay-tutorial_2019.11.20_2019.11.21.log](https://github.com/AVSystem/Anjay/files/3876727/anjay-tutorial_2019.11.20_2019.11.21.log)

**Comment by sznaider** [comment]
Please note that the examples are designed to illustrate certain points, and should be treated as an addition to Tutorials. They are by no means complete LwM2M clients. A more complete example is the `demo`.

Unfortunately, the log you've sent is not exactly what we asked for. We'd like to see the logs from the client side (not server side) + PCAP dumps to have a full picture of the underlying communication.

**Comment by ThinkpadX200** [comment]
I understand that they are not complete clients. Here are the client side logs. I will deliver the tcpdump soon.

[logs.txt](https://github.com/AVSystem/Anjay/files/3880209/logs.txt)

**Comment by sznaider** [comment]
> I am getting a specific error that the "Bootstrap Server misused Security Object" and I'm wondering why this error might occur?

It seems that the Bootstrap Server created two Bootstrap Security Instances (i.e. two Security Instances which have the Bootstrap-Server resource (`/0/*/1`) set to `true`), which in LwM2M is illegal. I may only guess that the intention was to create an instance of a Management Server instead, and that there's some mistake in the task executed on the server.
