### ISSUE TITLE
Anjay LwM2M & Quectel

### ISSUE THREAD

**Issue by cerealking-git** [AVSystem/Anjay#40]
I'm using Quectel BG96 and their evb (Quectel UMTS/LTE EVB KIT).
My goal is to build Anjay LwM2M Client and able to run it on current board.

From my quick research, it looks like Quectel is using LLVM to compile from Windows/Linux and need to follow their formats.
Beside follow their formats, is there way to compile Anjay with LLVM from Windows?
Kindly look into it.

**Comment by sznaider** [comment]
Hi,

It is definitely possible to use Anjay on BG96. What you're going to need is a proper CMake toolchain file. You'll also need to reimplement network layer to make use of QAPI functions.  See [our documentation](https://avsystem.github.io/Anjay-doc/Compiling_client_applications.html#cross-compiling) on how to get started with CMake toolchain file, and also our guide about [porting for non-POSIX platforms](https://avsystem.github.io/Anjay-doc/PortingGuideForNonPOSIXPlatforms.html).

Internally, we've already done a few integrations with the module, but don't currently plan to publicly release them. If you're interested in buying the whole integration or porting assistance, please contact sales@avsystem.com

**Comment by jiangshao6** [comment]
我最近也在做UMTS&LTE-EVB-KIT的相关项目，需要用AT指令发送数据到数据到服务器，这个开发板应该怎么使用？
