### ISSUE TITLE
Create C++ binding

### ISSUE THREAD

**Issue by henris42** [AVSystem/Anjay#42]
It might be beneficial to create a modern C++ binding on top on Anjay, as an external layer.
This binding could have advanced features like:
- Automatic management of resources, C callbacks etc
- Delegates
- entry/exit hooks in common lwm2m operations
- support for std::function, lambdas etc everywhere
- builder patterns
- C++ exceptions, threads etc

I've done some prototyping in this area, and its quite easy to get this type on binding where you can create and register new lwm2m objects in just few lines. This however should be done so that its open source and commonly available.

**Comment by Mierunski** [comment]
Hello,
Sorry for the late reply,
thank you for your input, we will take this possibility into consideration, contributions are also welcome.

Best Regards,
