### ISSUE TITLE
Script ./tools/lwm2m_object_registry.py can not connect with openmobilealliance.org

### ISSUE THREAD

**Issue by robgal519** [AVSystem/Anjay#43]
When I ran this script following the tutorial, I found out that the script is making http request (line 53) to url (line 58) and get 404 response.

I have no idea how long this endpoint is down, but it seems that the url should be updated.

**Comment by sznaider** [comment]
Thanks for the report. However, I think this must have been a temporary issue, as the script works for me at (tested it like a minute ago).

Does it work for you now?
