### ISSUE TITLE
ReadMe correction

### ISSUE THREAD

**Issue by rmiryala** [AVSystem/Anjay#46]
git clone https://github.com/AVSystem/Anjay.git
cd Anjay
docker build --tag anjay .

The above one yields error
I guess it has to be in the following way
git clone https://github.com/AVSystem/Anjay.git
cd Anjay
**git submodule update --init**
docker build --tag anjay .

**Comment by sznaider** [comment]
Thank you for the report! We've updated README.md accordingly in 2.4.3.
