### ISSUE TITLE
How to use NUCLEO-L476rg

### ISSUE THREAD

**Issue by anitakhb** [AVSystem/Anjay#51]
Hello there,

I am a beginner in using Anjay and I have a NUCLEO-L476 board with FreeRTOS and also a wiznet5100 board. How can I use Anjay on it?

Thank you for your support.

**Comment by Mierunski** [comment]
Hello,
Sorry for the late reply.
There is no official support for L476, but you can use anjay-freertos-client as reference, also there is a guide on how to port to different embedded systems https://avsystem.github.io/Anjay-doc/PortingGuideForNonPOSIXPlatforms.html
