### ISSUE TITLE
Configuration of DTLS using MbedTLS

### ISSUE THREAD

**Issue by tissoudali** [AVSystem/Anjay#52]
Hello,
I am interested in using Anjay library to define my LWM2M client, between the request that I have:
- I want to configure the DTLS stack using mbedtls (configure. h & dtlsclients. h), so that I can use the PSK that is stored in the secure element. Far as I know the only way to configure the DTLS in Anjay is by using the security Object, and the security object use the MbedTLS to open the connection & insure the HandShake with the LWM2M server.
- So my question is: how Anjay library implements the MbedTLS library?? And how can I modify DTLS stack in the MbedTLS using Anjay functions??

**Comment by tissoudali** [comment]
@dextero

**Comment by dextero** [comment]
Sorry, I'm not maintaining this library for some time now. @kFYatek, could you help?

**Comment by kFYatek** [comment]
Our glue code for Mbed TLS integration can be found at https://github.com/AVSystem/avs_commons/tree/master/src/crypto/mbedtls and https://github.com/AVSystem/avs_commons/tree/master/src/net/mbedtls.

If you want to use a secure element with the open source version, that would require custom modifications to the code. However, integration with hardware-based cryptography modules is available in the commercial version of Anjay. You can read a bit more about it in this blog post: https://www.avsystem.com/blog/hardware-security-module-support-in-anjay/

Please contact sales@avsystem.com if you're interested.
