### ISSUE TITLE
'binding_str' may be used uninitialized warning

### ISSUE THREAD

**Issue by AxelLin** [AVSystem/Anjay#58]
Below line has build issue when compile with riscv32 gcc.
https://github.com/AVSystem/Anjay/blob/master/src/modules/server/anjay_server_persistence.c#L286

anjay/deps/avs_commons/include_public/avsystem/commons/avs_log_impl.h:63:9: error: 'binding_str' may be used uninitialized in this function [-Werror=maybe-uninitialized]
         avs_log_internal_##Variant##__(Level, ModuleStr, __FILE__, __LINE__, \
         ^~~~~~~~~~~~~~~~~
anjay/src/modules/server/anjay_server_persistence.c:286:17: note: 'binding_str' was declared here
     const char *binding_str;
                 ^~~~~~~~~~~

**Comment by kFYatek** [comment]
This is a false positive and thus harmless. The `switch (binding)` statement, in all cases, either sets `binding_str` or sets `err = avs_errno(AVS_EBADMSG);`, and the only usage of `binding_str` below is under `if (avs_is_ok(err))` - the compiler is evidently not able to deduce the semantics of this check, hence the warning.

We will add some dummy initialization of this variable to silence this warning in future releases.
