### ISSUE TITLE
anajy_ipso_basic_sensor.c: update_curr_value

### ISSUE THREAD

**Issue by inimin** [AVSystem/Anjay#59]
Is there any reason for just notifying iid 0 change for each ipso object updating call ?

https://github.com/AVSystem/Anjay/blob/8fe0db09e60808dfa50edace6b1924de4eec9ad4/src/modules/ipso/anjay_ipso_basic_sensor.c#L173

**Comment by Mierunski** [comment]
Hi, looks like a typo from our side, thanks for the catch! There should be `iid` as a parameter.
We will fix it for the next release or you could provide a PR with the change

Best Regards
Mieszko
