### ISSUE TITLE
Float serialization bug?

### ISSUE THREAD

**Issue by scop** [AVSystem/Anjay#6]
Running the demo client (built on CentOS 7 or Ubuntu 16.04) from current git master against the Leshan demo server and watching the output in its web ui for location shows garbage for latitude, longitude,  altitude, and uncertainty values. I haven't noticed the problem with any other clients (e.g. wakaama's example lwm2mclient), and I don't see issues with any other data from Anjay, so I'm wondering if there's an issue with Anjay serializing floats? To reproduce:

$ ./output/bin/demo --server-uri coap://leshan.eclipse.org:5683

Go to http://leshan.eclipse.org/#/clients/urn:dev:os:0023C7-000001 and click the Read button in Location instance 0. Attached is a screenshot what it shows me at the moment.

![location](https://cloud.githubusercontent.com/assets/109152/24159968/48f2dc28-0e69-11e7-8d24-04c13eb82169.png)

**Comment by kFYatek** [comment]
I believe that http://leshan.eclipse.org/ is using an outdated definition of the Location object. Draft spec revisions up to and including [OMA-TS-LightweightM2M-V1_0-20161007-D](http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/Permanent_documents/OMA-TS-LightweightM2M-V1_0-20161007-D.zip) actually defined those four parameters as decimal Strings. [OMA-TS-LightweightM2M-V1_0-20161031-D](http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/Permanent_documents/OMA-TS-LightweightM2M-V1_0-20161031-D.zip) and later (which includes the final 1.0 TS) define them as Floats.

It seems to be further confirmed by the fact that the garbage on the screenshot above looks very similar to a binary Float value printed as a string, as can be observed here:
```
kfyatek@kfyatek:~$ python
Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
[GCC 6.2.0 20160914] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import struct
>>> struct.pack('>d', 50.083463)
'@I\n\xae\xeac\xb6\x89'
>>> print('%s' % struct.pack('>d', 50.083463))
@I
��c��
```

**Comment by scop** [comment]
Ah! I concur, PR sent to Leshan, thanks.
